class AppStringKeys {
  AppStringKeys._();

  static const welcome = 'welcome';
  static const email = 'email';
  static const password = 'password';
  static const enterPassword = 'Enter Password';
  static const login = 'login';
  static const register = 'register';
  static const userManagement = 'user_management';
  static const otpRequired = 'otp_required';
  static const invalidOtp = 'invalid_otp';
  static const searchUsers = 'search_users';
  static const error = 'error';
}

class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> value = {
    "en":{
      "Welcome":"Welcome",
      "first_name":"First Name",
      "last_name":"Last Name",
      "email":"Email",
      "phone_number":"Phone Number",
      "dob":"Date of Birth",
      "enter_first_name":"Enter First Name",
      "enter_last_name":"Enter Last Name",
      "enter_email":"Enter Email",
      "enter_phone_number":"Enter Phone Number",
      "enter_dob":"Enter Date of Birth",
      "first_name_required":"First Name is required",
      "last_name_required":"Last Name is required",
      "email_required":"Email is required",
      "phone_number_required":"Phone Number is required",
      "dob_required":"Date of Birth is required",
      "otp_verification": "OTP Verification",
      "enter_otp_message": "Enter the 6-digit OTP sent to your email",
      "enter_otp": "Enter OTP",
      "otp_required": "OTP is required",
      "otp_invalid": "OTP must contain exactly 6 digits",
      "verify_otp": "Verify OTP",
      "resend_otp": "Resend OTP",
      "otp_resent_successfully": "OTP Resent Successfully",
      "demo_otp": "Demo OTP: 123456",
      "invalid_otp": "Invalid OTP",
      "phone": "Phone",
      "date_of_birth": "Date of Birth",
      "logout": "Logout",
      "users": "Users",
      "my_profile": "My Profile",
      "profile": "Profile", //
      "welcome": "Welcome",
      "user_dashboard": "User Dashboard",
      "welcome_back": "Welcome Back",
      "login_to_continue": "Login to continue",
      "login": "Login",
      "new_user": "New User?",
      "register": "Register",
      "enter_valid_gmail": "Enter a valid Gmail address",
      "example_email": "example@gmail.com",
      "settings": "Settings",
      "theme": "Theme",
      "light": "Light",
      "dark": "Dark",
      "language": "Language",
      "close": "Close",
      "english": "English",
      "arabic": "Arabic",
      "user_management": "User Management",
      "create_account": "Create Account",
      "fill_details": "Fill in your details to register",
      "select_dob": "Select Date of Birth",
      "already_have_account": "Already have an account?",
      "valid_phone": "Enter a valid 10-digit phone number",
      "user_details": "User Details",
      "name": "Name",
      "education": "Education",
      "gender": "Gender",
      "password": "Password",
      "password_required": "Password is required",
      "password_length": "Password must be at least 6 characters long",
      "Enter Password": "Enter Password",
      "enter_date_of_birth": "Enter Date of Birth",
      "search_users": "Search users...",
      "error": "Error",
    },

    "ar":{
      "Welcome":"أهلا بك",
      "first_name":"الاسم الأول",
      "last_name":"الكنية",
      "email":"البريد الإلكتروني",
      "phone_number":"رقم الهاتف",
      "dob":"تاريخ الولادة",
      "enter_first_name":"أدخل الاسم الأول",
      "enter_last_name":"أدخل اسم العائلة",
      "enter_email":"أدخل البريد الإلكتروني",
      "enter_phone_number":"أدخل رقم الهاتف",
      "enter_dob":"أدخل تاريخ الميلاد",
      "first_name_required":"الاسم الأول مطلوب",
      "last_name_required":"اسم العائلة مطلوب",
      "email_required":"البريد الإلكتروني مطلوب",
      "phone_number_required":"رقم الهاتف مطلوب",
      "dob_required":"تاريخ الميلاد مطلوب",
      "otp_verification": "التحقق من رمز OTP",
      "enter_otp_message": "أدخل رمز OTP المكون من 6 أرقام المرسل إلى بريدك الإلكتروني",
      "enter_otp": "أدخل رمز OTP",
      "otp_required": "رمز OTP مطلوب",
      "otp_invalid": "يجب أن يحتوي رمز OTP على 6 أرقام بالضبط",
      "verify_otp": "تحقق من OTP",
      "resend_otp": "إعادة إرسال OTP",
      "otp_resent_successfully": "تمت إعادة إرسال رمز OTP بنجاح",
      "demo_otp": "رمز OTP التجريبي: 123456",
      "invalid_otp": "رمز OTP غير صالح",
      "phone": "الهاتف",
      "date_of_birth": "تاريخ الميلاد",
      "logout": "تسجيل الخروج",
      "users": "المستخدمون",
      "my_profile": "ملفي الشخصي",
      "profile": "الملف الشخصي",
      "welcome": "أهلاً",
      "user_dashboard": "لوحة تحكم المستخدم",
      "welcome_back": "مرحبًا بعودتك",
      "login_to_continue": "سجل الدخول للمتابعة",
      "login": "تسجيل الدخول",
      "new_user": "مستخدم جديد؟",
      "register": "تسجيل",
      "enter_valid_gmail": "أدخل عنوان Gmail صالحًا",
      "example_email": "example@gmail.com",
      "settings": "الإعدادات",
      "theme": "المظهر",
      "light": "فاتح",
      "dark": "داكن",
      "language": "اللغة",
      "close": "إغلاق",
      "english": "الإنجليزية",
      "arabic": "العربية",
      "user_management": "إدارة المستخدمين",
      "create_account": "إنشاء حساب",
      "fill_details": "املأ بياناتك للتسجيل",
      "select_dob": "اختر تاريخ الميلاد",
      "already_have_account": "هل لديك حساب بالفعل؟",
      "valid_phone": "أدخل رقم هاتف صالحًا مكونًا من 10 أرقام",
      "user_details": "تفاصيل المستخدم",
      "name": "الاسم",
      "education": "التعليم",
      "gender": "الجنس",
      "password": "كلمة المرور",
      "password_required": "كلمة المرور مطلوبة",
      "password_length": "يجب أن تكون كلمة المرور مكونة من 6 أحرف على الأقل",
      "Enter Password": "أدخل كلمة المرور",
      "enter_date_of_birth": "أدخل تاريخ الميلاد",
      }
  };
}
